export const dataStudentOfAdmin = [
    {
        hocVien: "Nguyễn Văn An",
        zalo: "0901234567",
        khoaHoc: "Web Dev",
        donVi: "BCN",
        trangThai: "Đang học",
    },
    {
        hocVien: "Trần Thị Bình",
        zalo: "0912345678",
        khoaHoc: "App Dev",
        donVi: "Uside",
        trangThai: "Không HĐ",
    },
    {
        hocVien: "Lê Hoàng Cường",
        zalo: "0983456789",
        khoaHoc: "Cơ Bản",
        donVi: "BCN",
        trangThai: "Đang học",
    },
    {
        hocVien: "Phạm Thu Dung",
        zalo: "0974567890",
        khoaHoc: "Design",
        donVi: "Uside",
        trangThai: "Đang học",
    },
    {
        hocVien: "Hoàng Minh Duy",
        zalo: "0355678901",
        khoaHoc: "Web Dev",
        donVi: "Uside",
        trangThai: "Không HĐ",
    },
    {
        hocVien: "Vũ Thị Hoa",
        zalo: "0366789012",
        khoaHoc: "Cơ Bản",
        donVi: "BCN",
        trangThai: "Đang học",
    },
    {
        hocVien: "Phan Khắc Hải",
        zalo: "0377890123",
        khoaHoc: "App Dev",
        donVi: "BCN",
        trangThai: "Không HĐ",
    },
    {
        hocVien: "Bùi Ngọc Lan",
        zalo: "0388901234",
        khoaHoc: "Design",
        donVi: "Uside",
        trangThai: "Đang học",
    },
    {
        hocVien: "Đặng Quốc Khánh",
        zalo: "0399012345",
        khoaHoc: "Web Dev",
        donVi: "BCN",
        trangThai: "Không HĐ",
    },
    {
        hocVien: "Hồ Bích Ngọc",
        zalo: "0811123456",
        khoaHoc: "Cơ Bản",
        donVi: "Uside",
        trangThai: "Đang học",
    },
    {
        hocVien: "Ngô Trí Phong",
        zalo: "0822234567",
        khoaHoc: "App Dev",
        donVi: "Uside",
        trangThai: "Đang học",
    },
    {
        hocVien: "Dương Thanh Quỳnh",
        zalo: "0833345678",
        khoaHoc: "Design",
        donVi: "BCN",
        trangThai: "Đang học",
    },
    {
        hocVien: "Lý Bảo Quốc",
        zalo: "0844456789",
        khoaHoc: "Web Dev",
        donVi: "Uside",
        trangThai: "Không HĐ",
    },
    {
        hocVien: "Đỗ Cẩm Tú",
        zalo: "0855567890",
        khoaHoc: "Cơ Bản",
        donVi: "BCN",
        trangThai: "Đang học",
    },
    {
        hocVien: "Trương Viết Vũ",
        zalo: "0866678901",
        khoaHoc: "App Dev",
        donVi: "BCN",
        trangThai: "Không HĐ",
    },
];
